# Generated by Django 5.0.6 on 2026-06-03 17:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteEpargne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('devise', models.CharField(choices=[('USD', 'Dollar américain (USD)'), ('CDF', 'Franc congolais (CDF)')], max_length=3)),
                ('solde', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('objectif_montant', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('objectif_description', models.CharField(blank=True, max_length=255)),
                ('date_objectif', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_epargne', to='clients.client')),
            ],
            options={
                'db_table': 'compte_epargne',
            },
        ),
        migrations.CreateModel(
            name='OperationEpargne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_operation', models.CharField(choices=[('depot', 'Dépôt'), ('retrait', 'Retrait')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('solde_avant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('solde_apres', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('id_compte_epargne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='savings.compteepargne')),
            ],
            options={
                'db_table': 'operation_epargne',
                'ordering': ['-date_operation'],
            },
        ),
        migrations.AddIndex(
            model_name='compteepargne',
            index=models.Index(fields=['id_client', 'devise'], name='compte_epar_id_clie_6a49ab_idx'),
        ),
    ]
