# Generated by Django 5.0.6 on 2026-06-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationepargne',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('', 'Interne / virement'), ('illicocash', 'Illico Cash'), ('mpesa', 'Vodacom M-Pesa'), ('orange_money', 'Orange Money'), ('airtel_money', 'Airtel Money'), ('africell', 'Africell Money')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='operationepargne',
            name='numero_paiement',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='operationepargne',
            name='reference_externe',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
