# Generated by Django 5.0.6 on 2026-06-03 23:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_platform_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='maintenance_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='mfa_obligatoire_agents',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='session_timeout_minutes',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='usd_agent_auto_max',
            field=models.DecimalField(decimal_places=2, default=Decimal('400.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Plafond auto-approbation agent (USD)'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='usd_credit_max',
            field=models.DecimalField(decimal_places=2, default=Decimal('1500.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='usd_credit_min',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='usd_manager_max',
            field=models.DecimalField(decimal_places=2, default=Decimal('1200.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Plafond validation responsable (USD)'),
        ),
    ]
