# Generated by Django 5.0.6 on 2026-06-03 17:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMoneyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operateur', models.CharField(choices=[('mpesa', 'Vodacom M-Pesa'), ('orange_money', 'Orange Money'), ('airtel_money', 'Airtel Money'), ('africell', 'Africell Money')], max_length=50)),
                ('numero_telephone', models.CharField(max_length=20)),
                ('devise', models.CharField(choices=[('USD', 'Dollar américain (USD)'), ('CDF', 'Franc congolais (CDF)')], default='CDF', max_length=3)),
                ('date_liaison', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mm_accounts', to='clients.client')),
            ],
            options={
                'db_table': 'mobile_money_account',
                'unique_together': {('id_client', 'operateur', 'numero_telephone', 'devise')},
            },
        ),
        migrations.CreateModel(
            name='MobileMoneyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('devise', models.CharField(choices=[('USD', 'Dollar américain (USD)'), ('CDF', 'Franc congolais (CDF)')], max_length=3)),
                ('type_transaction', models.CharField(choices=[('depot', 'Dépôt'), ('transfert_sortant', 'Transfert sortant'), ('reception', 'Réception'), ('paiement_facture', 'Paiement facture'), ('retrait', 'Retrait')], max_length=30)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('solde_apres', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_transaction', models.DateTimeField()),
                ('reference_externe', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('id_mm_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallets.mobilemoneyaccount')),
            ],
            options={
                'db_table': 'mobile_money_transaction',
                'indexes': [models.Index(fields=['id_mm_account', 'date_transaction'], name='mobile_mone_id_mm_a_39250b_idx'), models.Index(fields=['type_transaction'], name='mobile_mone_type_tr_916701_idx'), models.Index(fields=['devise'], name='mobile_mone_devise_882969_idx')],
            },
        ),
        migrations.CreateModel(
            name='WalletRawbank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('devise', models.CharField(choices=[('USD', 'Dollar américain (USD)'), ('CDF', 'Franc congolais (CDF)')], max_length=3)),
                ('numero_wallet', models.CharField(max_length=30, unique=True)),
                ('solde', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('gele', 'Gelé'), ('inactif', 'Inactif')], default='actif', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='clients.client')),
            ],
            options={
                'db_table': 'wallet_rawbank',
                'indexes': [models.Index(fields=['id_client', 'devise'], name='wallet_rawb_id_clie_e0124a_idx')],
                'unique_together': {('id_client', 'devise')},
            },
        ),
    ]
