# Generated by Django 5.0.6 on 2026-06-29 08:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_transaction', models.CharField(choices=[('depot', 'Dépôt'), ('retrait', 'Retrait')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('solde_avant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('solde_apres', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mode_paiement', models.CharField(choices=[('illicocash', 'Illico Cash'), ('mpesa', 'Vodacom M-Pesa'), ('orange_money', 'Orange Money'), ('airtel_money', 'Airtel Money'), ('africell', 'Africell Money')], max_length=50)),
                ('numero_paiement', models.CharField(blank=True, max_length=20)),
                ('reference_externe', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallets.walletrawbank')),
            ],
            options={
                'db_table': 'wallet_transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', 'created_at'], name='wallet_tran_wallet__a053af_idx'), models.Index(fields=['type_transaction'], name='wallet_tran_type_tr_2ea339_idx')],
            },
        ),
    ]
