# Generated by Django 5.0.6 on 2026-06-03 17:16

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreComportemental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('features_used', models.JSONField(default=dict)),
                ('date_calcul', models.DateTimeField(auto_now_add=True)),
                ('id_demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_comportemental', to='credits.demandecredit')),
            ],
            options={
                'db_table': 'score_comportemental',
            },
        ),
        migrations.CreateModel(
            name='ScoreIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('probabilite_defaut', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=5)),
                ('niveau_risque', models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('eleve', 'Élevé')], default='moyen', max_length=20)),
                ('score_normalise', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('modele_utilise', models.CharField(default='XGBoost_v2', max_length=100)),
                ('shap_values', models.JSONField(default=dict)),
                ('lime_values', models.JSONField(default=dict)),
                ('feature_vector', models.JSONField(default=dict)),
                ('date_prediction', models.DateTimeField(auto_now_add=True)),
                ('id_demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_ia', to='credits.demandecredit')),
            ],
            options={
                'db_table': 'score_ia',
            },
        ),
        migrations.CreateModel(
            name='ScoreMobileMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('features_used', models.JSONField(default=dict)),
                ('date_calcul', models.DateTimeField(auto_now_add=True)),
                ('id_demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_mobile_money', to='credits.demandecredit')),
            ],
            options={
                'db_table': 'score_mobile_money',
            },
        ),
        migrations.CreateModel(
            name='ScoreRegle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('resultat', models.BooleanField(default=False)),
                ('details', models.JSONField(default=dict)),
                ('date_calcul', models.DateTimeField(auto_now_add=True)),
                ('id_demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_regle', to='credits.demandecredit')),
            ],
            options={
                'db_table': 'score_regle',
            },
        ),
        migrations.CreateModel(
            name='DecisionCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('mise_en_attente', 'Mise en attente')], max_length=20)),
                ('score_global', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('motif', models.TextField(blank=True)),
                ('explication_ia', models.TextField(blank=True)),
                ('is_automatic', models.BooleanField(default=True)),
                ('date_decision', models.DateTimeField(auto_now_add=True)),
                ('id_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_prises', to=settings.AUTH_USER_MODEL)),
                ('id_demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='credits.demandecredit')),
            ],
            options={
                'db_table': 'decision_credit',
                'indexes': [models.Index(fields=['decision', 'date_decision'], name='decision_cr_decisio_af65a0_idx')],
            },
        ),
    ]
