# Generated by Django 5.0.6 on 2026-06-03 23:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('kyc', 'KYC'), ('montant', 'Montant'), ('comportement', 'Comportement'), ('mobile_money', 'Mobile Money'), ('general', 'Général')], default='general', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scoring_rule',
                'ordering': ['category', 'code'],
            },
        ),
    ]
