# Generated by Django 5.0.6 on 2026-06-27 04:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_model_training_run'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='modeltrainingrun',
            new_name='model_train_model_n_23fcd9_idx',
            old_name='model_train_model_n_2b4d6e_idx',
        ),
        migrations.AlterField(
            model_name='modeltrainingrun',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
