# Generated by Django 5.0.6 on 2026-06-03 17:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_role', models.CharField(choices=[('Client', 'Client'), ('Agent de crédit', 'Agent de crédit'), ('Responsable crédit', 'Responsable crédit'), ('Analyste risque', 'Analyste risque'), ('Administrateur', 'Administrateur'), ('Auditeur', 'Auditeur')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('postnom', models.CharField(blank=True, max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=150, null=True, unique=True)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('bloque', 'Bloqué'), ('suspendu', 'Suspendu')], default='actif', max_length=20)),
                ('mfa_secret', models.CharField(blank=True, max_length=64)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('mfa_verified', models.BooleanField(default=False)),
                ('failed_login_attempts', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='authentication.role')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'db_table': 'utilisateur',
                'indexes': [models.Index(fields=['telephone'], name='utilisateur_telepho_ee0c27_idx'), models.Index(fields=['statut'], name='utilisateur_statut_e66b29_idx')],
            },
        ),
    ]
