# Generated by Django 5.0.6 on 2026-06-04 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='last_device_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='last_login_country',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
