# Generated by Django 5.0.6 on 2026-06-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_utilisateur_last_device_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='commune_kinshasa',
            field=models.CharField(blank=True, choices=[('bandalungwa', 'Bandalungwa'), ('barumbu', 'Barumbu'), ('bumbu', 'Bumbu'), ('gombe', 'Gombe'), ('kalamu', 'Kalamu'), ('kasa_vubu', 'Kasa-Vubu'), ('kimbanseke', 'Kimbanseke'), ('kinshasa', 'Kinshasa'), ('kintambo', 'Kintambo'), ('kisenso', 'Kisenso'), ('lemba', 'Lemba'), ('limete', 'Limete'), ('lingwala', 'Lingwala'), ('makala', 'Makala'), ('maluku', 'Maluku'), ('masina', 'Masina'), ('matete', 'Matete'), ('mont_ngafula', 'Mont-Ngafula'), ('ndjili', "N'djili"), ('ngaba', 'Ngaba'), ('ngaliema', 'Ngaliema'), ('ngiri_ngiri', 'Ngiri-Ngiri'), ('nsele', 'Nsele'), ('selembao', 'Selembao')], default='', help_text='Commune Kinshasa (agents de crédit)', max_length=40),
        ),
    ]
