# Generated by Django 5.0.6 on 2026-06-03 17:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profession', models.CharField(blank=True, max_length=150)),
                ('adresse', models.TextField(blank=True)),
                ('date_naissance', models.DateField()),
                ('revenu_estime_usd', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Revenu estimé (USD)')),
                ('revenu_estime_cdf', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Revenu estimé (CDF)')),
                ('niveau_risque', models.CharField(choices=[('non_evalue', 'Non évalué'), ('faible', 'Faible'), ('moyen', 'Moyen'), ('eleve', 'Élevé')], default='non_evalue', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('id_utilisateur', models.OneToOneField(db_column='id_utilisateur', on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Identite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_piece', models.CharField(choices=[('carte_electeur', "Carte d'électeur"), ('passeport', 'Passeport'), ('permis_conduire', 'Permis de conduire'), ('carte_consulaire', 'Carte consulaire')], max_length=50)),
                ('numero_piece', models.CharField(max_length=100, unique=True)),
                ('date_expiration', models.DateField()),
                ('statut_verification', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=30)),
                ('date_verification', models.DateTimeField(blank=True, null=True)),
                ('document_scan', models.FileField(blank=True, null=True, upload_to='kyc/scans/%Y/%m/')),
                ('rejection_reason', models.TextField(blank=True)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identites', to='clients.client')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Identité',
                'db_table': 'identite',
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['niveau_risque'], name='client_niveau__2e7cba_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['date_inscription'], name='client_date_in_00e71f_idx'),
        ),
    ]
