# Generated by Django 5.0.6 on 2026-06-14 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='commune_kinshasa',
            field=models.CharField(blank=True, choices=[('bandalungwa', 'Bandalungwa'), ('barumbu', 'Barumbu'), ('bumbu', 'Bumbu'), ('gombe', 'Gombe'), ('kalamu', 'Kalamu'), ('kasa_vubu', 'Kasa-Vubu'), ('kimbanseke', 'Kimbanseke'), ('kinshasa', 'Kinshasa'), ('kintambo', 'Kintambo'), ('kisenso', 'Kisenso'), ('lemba', 'Lemba'), ('limete', 'Limete'), ('lingwala', 'Lingwala'), ('makala', 'Makala'), ('maluku', 'Maluku'), ('masina', 'Masina'), ('matete', 'Matete'), ('mont_ngafula', 'Mont-Ngafula'), ('ndjili', "N'djili"), ('ngaba', 'Ngaba'), ('ngaliema', 'Ngaliema'), ('ngiri_ngiri', 'Ngiri-Ngiri'), ('nsele', 'Nsele'), ('selembao', 'Selembao')], db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='client',
            name='id_agent_assigne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_affectes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['commune_kinshasa'], name='client_commune_8c5a78_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['commune_kinshasa', 'id_agent_assigne'], name='client_commune_0fadbf_idx'),
        ),
    ]
