# Generated by Django 5.0.6 on 2026-06-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_territoire_kinshasa'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='niveau_compte',
            field=models.CharField(choices=[('standard', 'Standard'), ('pro', 'Pro'), ('pro_plus', 'Pro+'), ('premium', 'Premium')], db_index=True, default='standard', max_length=20),
        ),
    ]
