# Generated by Django 5.0.6 on 2026-06-03 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VectorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('source', models.CharField(blank=True, max_length=255)),
                ('document_type', models.CharField(default='policy', max_length=100)),
                ('embedding', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vector_document',
            },
        ),
    ]
