# Generated by Django 5.0.6 on 2026-06-03 17:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('devise', models.CharField(choices=[('USD', 'Dollar américain (USD)'), ('CDF', 'Franc congolais (CDF)')], default='USD', max_length=3)),
                ('montant_demande', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('duree_mois', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('motif', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_analyse', 'En analyse'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('cloture', 'Clôturé'), ('annule', 'Annulé')], default='en_analyse', max_length=30)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_credit', to='clients.client')),
            ],
            options={
                'db_table': 'demande_credit',
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant_accorde', models.DecimalField(decimal_places=2, max_digits=15)),
                ('taux_interet', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('rembourse', 'Remboursé'), ('defaut', 'Défaut'), ('radie', 'Radié')], default='en_cours', max_length=20)),
                ('id_demande', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='credit', to='credits.demandecredit')),
            ],
            options={
                'db_table': 'credit',
            },
        ),
        migrations.CreateModel(
            name='Echeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_echeance', models.DateField(db_index=True)),
                ('statut', models.CharField(choices=[('non_paye', 'Non payé'), ('paye', 'Payé'), ('en_retard', 'En retard'), ('partiellement_paye', 'Partiellement payé')], default='non_paye', max_length=30)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('id_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='credits.credit')),
            ],
            options={
                'db_table': 'echeance',
                'ordering': ['date_echeance'],
            },
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('mode_paiement', models.CharField(choices=[('illicocash', 'illicocash'), ('virement', 'Virement bancaire'), ('agence', 'Agence Rawbank'), ('mobile_money', 'Mobile Money')], default='illicocash', max_length=50)),
                ('reference_transaction', models.CharField(blank=True, max_length=100)),
                ('echeance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remboursements', to='credits.echeance')),
                ('id_credit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remboursements', to='credits.credit')),
            ],
            options={
                'db_table': 'remboursement',
            },
        ),
        migrations.AddIndex(
            model_name='demandecredit',
            index=models.Index(fields=['id_client', 'statut'], name='demande_cre_id_clie_0a00de_idx'),
        ),
        migrations.AddIndex(
            model_name='demandecredit',
            index=models.Index(fields=['statut', 'date_demande'], name='demande_cre_statut_61cbc9_idx'),
        ),
        migrations.AddIndex(
            model_name='demandecredit',
            index=models.Index(fields=['devise'], name='demande_cre_devise_c69c52_idx'),
        ),
    ]
