# Generated by Django 5.0.6 on 2026-06-03 23:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('credits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_exception', models.CharField(choices=[('plafond', 'Dépassement plafond'), ('kyc', 'KYC exceptionnel'), ('delai', 'Délai de grâce'), ('autre', 'Autre')], default='autre', max_length=30)),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée'), ('cloturee', 'Clôturée')], default='ouverte', max_length=20)),
                ('observation', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions_creees', to=settings.AUTH_USER_MODEL)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exceptions_credit', to='clients.client')),
                ('id_demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions', to='credits.demandecredit')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions_resolues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_exception',
                'ordering': ['-created_at'],
            },
        ),
    ]
